"""Compiler option tuning agent package."""

from .config import AgentConfig, ConfigLoadError, load_config
from .init import (
    HistorySummary,
    InitAborted,
    InitContext,
    InitEditRequested,
    InitError,
    InitializedLoadError,
    InitializedState,
    InitResult,
    NamespaceMismatchError,
    assert_initialized_matches,
    collect_history_summary,
    load_initialized_state,
    normalize_init_choice,
    prepare_init_context,
    prompt_for_init_confirmation,
    render_init_confirmation,
    run_init,
    verify_initialized_for_startup,
    write_initialized_state,
)
from .registry import (
    ModulesRegistry,
    ProjectNamespace,
    RegistryLoadError,
    RegistryValidationError,
    compute_project_namespace,
    load_modules_registry,
    registry_path_for_workspace,
    validate_project_against_registry,
)
from .workspace_lock import (
    LockReadResult,
    WorkspaceBusyError,
    WorkspaceLock,
    WorkspaceLockError,
    WorkspaceLockHolder,
    WorkspaceLockPlatformError,
    lock_path_for_workspace,
)

__all__ = [
    "AgentConfig",
    "ConfigLoadError",
    "HistorySummary",
    "InitAborted",
    "InitContext",
    "InitEditRequested",
    "InitError",
    "InitializedLoadError",
    "InitializedState",
    "InitResult",
    "LockReadResult",
    "ModulesRegistry",
    "NamespaceMismatchError",
    "ProjectNamespace",
    "RegistryLoadError",
    "RegistryValidationError",
    "WorkspaceBusyError",
    "WorkspaceLock",
    "WorkspaceLockError",
    "WorkspaceLockHolder",
    "WorkspaceLockPlatformError",
    "assert_initialized_matches",
    "collect_history_summary",
    "compute_project_namespace",
    "load_config",
    "load_initialized_state",
    "load_modules_registry",
    "lock_path_for_workspace",
    "normalize_init_choice",
    "prepare_init_context",
    "prompt_for_init_confirmation",
    "registry_path_for_workspace",
    "render_init_confirmation",
    "run_init",
    "validate_project_against_registry",
    "verify_initialized_for_startup",
    "write_initialized_state",
]
